env:
  global:
    - secure: CxF13OtnMWaa6RBSn9uS4TZbBmMIrpZlF9LcBsEK2m0IhbqsKyG6uaeB/FgafHWRqqJXznVTMPB9HfZK/rGX+E6b1Eo+0KozRGEoVGhgjKSMtV8w8JE3YtZlFXTIVuOv9GE19LSMRft5sfCFWuVNUuVsLuQQgsOYrjw9ALDMXL3WFF2fWWW+7buPz2d21yZ+0vj//Xcoh8II9C2ZPGLwHfzkhy52aYXLtYwBB/fRDuQLYWjtg+3VY8rgR2aVSEKPvj3GkKG8qY/Ncc1vhzErTJ9B1eB1cFWwXoRljozTYk+ncSOY8laqjlTomTsIGCqRIBWcSvr1xP/dhx4hdJju1rk2ojesP8qVamteygnzBDAH8lbD363Z1yf7PgyjjZhpYJq1cK9rSNJL9cNeYsTZesMLm/+qQNeT26BeZatHQxane2Ep/pLi7+vCd6fSFCvdmRuaY3bq/SlFtJdhx9QzR083xqUQKeo7hUpXNbQeDTuQ4q+5bYgv83VZwImqT1lj11VHKCnE7aBn9C9JZcyulH7//I8smEhsnrGxDFzzs4Ag835PH7wvWK7oLGVinaTqGNmgZvSff5Oh+NK3rLtqMTkIHbwgmcX++qc/CRVqGNimrCVJp2VcA3uMTiWbH7Q2nzdUgsWj6wcQYtZyVBNpgicCqLpXVgpzOg0pa7rG3ps=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/anudeepND_blacklist_ad_server
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
