env:
  global:
    - secure: PKRnvvTpj+7zUbvm8XtzjV8JHSv0musM4PNJ6+x8WgLGN4ZCWFAx1nzm1Tta0gs+P+quOpXhvCwE4A13MQKjAjhbVvbDFOrvlh5oezni+fIrwDdNAg/jVDblqQvClPBfJrSlVzywyLmRX+5bL5Xs0dcXEGcma43fR7lCl/KEe4lcymwwZ8OWWIPRXrqAd6d+7qQMlRBXh1EM78AtzHBfe39/dl0OdaEYB/nSaF9CAoMbfrytuaZr7Di6SPwsYgvf56D7YPky9DsBrCTmAhNLqUpzkfyl3XlYd6jgd6BpdzyDE9NxRjwsoDO62fqIW9YRVKj7h1wOP7klpzQBZit3a9+/u/GAUKN/TPbQesUnhIUlK42TG0VybdfbP6dADcEYKJe7O9zSm/BNpYK+4QTYE2L4db0E8cSVUUVKtVAbdNdAhq3YkogfYVcYGY6qEWCuXZdC4bKRJIcuY+7YrRQ8+65MwljFroIIdXvH8BtKzAitb4JAqPoqlcyuZZt5gPHDZ78+LSl2qag1y+QF+/4wfalj4a4Z3YrAhfC9uTTK0SHI+gTpFo9K0yb+VTa1vpeNeEuAIrvZA5beLbMhKGqUPsMwyMO1A3m9nCCYl5/MfmjIFzcOKekSaLHwQIACE7xp35vFLyve9OaF0bwqJXFMINI+UtrMP04YwddsfXPuoV0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/anudeepND_blacklist_ad_server
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
