env:
  global:
    - secure: kibjnJkedExCuovfuzindAzPFhqMWZSQJ/Ub6hKzJ4jyBA2f0qcZlnzoiDIdgJXBgxuhEYC8cKnrJuu+RH7eViJxAXiPgfOmDX5S+kuOhdjDb7dcbCNdaHU9eqYfzEUwMWL9ca0s0TF/slID7lJlf+n6wQlLWJ+qLeZG7s7diNAfoRTF6+ziRTFB+KvrGLjeydE7pShR+xPHqoa41mgJOTpwD9QEgUaFEtsvb02t6GOZ/bgQlXbCZcfYKqHkfdIZZXXW4QV30PjCwB3G+LdkCQJ9hpXjrLQDecd9Y1v1NeSH+LexSeUjk8oUftMOA6YTfpGTmSwgwzdnsYIC4UxC1WK7G8drkE5qd8pVgYxPWhPmNQcVXmXB0c98y4lbuS26Supj2U3xWoqj2KRuEpnhc8AZDYApDl3ytiQx6vbj9fAJV5jzeLGJwE6UmlCtCNqg8AR1ZInbld0KcBRQ6NLGUFop/PdqzVIDommn3T7E3h9h09v2h56xQNDSq89kjK4P83Kcef7hGrl1rF4QoKqbPSI6pnpu0oahCPFnuqmxm65KiT7wWNnWc1caoFfZZqpdrjSu0uZyYDoDI7dFl2BF6oGgvL160YHXVa4nstqiy8TmD1DAfm88y3JwdVB9LT2+E+OTSAbAeEFBeI1OK/Zpo3hUdb3RudNS0EfLH32zogg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/anudeepND_blacklist_ad_server
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
